REASON_EXCLUDED_KEYWORDS = "conta com termos excluidos"
REASON_WORK_MODE_MISMATCH = "modalidade fora do perfil"
REASON_SALARY_BELOW_MINIMUM = "salario abaixo do minimo"
REASON_SENIORITY_OUTSIDE_TARGET = "senioridade fora do alvo"
REASON_UNKNOWN_SENIORITY = "senioridade nao informada"
